#ifndef SUI_H
#define SUI_H

#include "SUI_main.h"
#include "SUI_window.h"
#include "SUI_button.h"
#include "SUI_color.h"
#include "SUI_decorator.h"
#include "SUI_drawable.h"
#include "SUI_event_handler.h"
#include "SUI_events.h"
#include "SUI_geometry.h"
#include "SUI_graphic_board_base.h"
#include "SUI_graphic_board.h"
#include "SUI_image.h"
#include "SUI_object.h"
#include "SUI_property.h"
#include "SUI_shape.h"
#include "SUI_styles.h"
#include "SUI_utils.h"
#include "SUI_tool.h"
#include "SUI_pane.h"
#include "SUI_pane_grid.h"
#include "SUI_pane_horizontal.h"
#include "SUI_pane_vertical.h"
#include "SUI_dialog.h"
#include "SUI_label.h"
#include "SUI_text_area.h"
#include "SUI_opengl_graphic.h"
#include "SUI_slider.h"

#endif